name: Windows打包EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 配置Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 安装Rust编译工具链
        uses: dtolnay/rust-toolchain@stable

      - name: 安装项目全部依赖
        run: cd desktop && pnpm install

      - name: Tauri编译打包Windows安装程序
        run: cd desktop && pnpm exec tauri build

      - name: 上传打包后的EXE安装包
        uses: actions/upload-artifact@v4
        with:
          name: OpenCodex-Windows安装包
          path: desktop/src-tauri/target/release/bundle/msi/*.exe
